repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: detect-private-key
      - id: forbid-new-submodules
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.8.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/pre-commit/mirrors-fixmyjs
    rev: v2.0.0
    hooks:
      - id: fixmyjs
        args: ["-l", "-c", ".jshintrc"]
  # - repo: https://github.com/pre-commit/mirrors-jshint
  #   rev: v2.11.0
  #   hooks:
  #     - id: jshint
